# Generated by Django 3.1.7 on 2021-03-17 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSiswa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nisn', models.CharField(blank=True, max_length=200)),
                ('asal_sekolah', models.CharField(blank=True, max_length=200)),
                ('tahun_lulus', models.CharField(blank=True, max_length=200)),
                ('p_ijazah', models.FileField(blank=True, upload_to='files/ijazah/')),
                ('nama_lengkap', models.CharField(blank=True, max_length=200)),
                ('nik', models.CharField(blank=True, max_length=200)),
                ('tempat_lahir', models.CharField(blank=True, max_length=200)),
                ('tanggal_lahir', models.DateField(blank=True, null=True)),
                ('p_akte', models.FileField(blank=True, upload_to='files/akte/')),
                ('jenis_kelamin', models.CharField(blank=True, choices=[('Laki-Laki', 'Laki-Laki'), ('Perempuan', 'Perempuan')], max_length=200)),
                ('alamat', models.CharField(blank=True, max_length=200)),
                ('desa', models.CharField(blank=True, max_length=200)),
                ('kecamatan', models.CharField(blank=True, max_length=200)),
                ('kabupaten', models.CharField(blank=True, max_length=200)),
                ('provinsi', models.CharField(blank=True, max_length=200)),
                ('email', models.CharField(blank=True, max_length=200)),
                ('no_kk', models.CharField(blank=True, max_length=200)),
                ('p_no_kk', models.FileField(blank=True, upload_to='files/kk/')),
                ('kks', models.FileField(blank=True, upload_to='file/kks/')),
                ('pkh', models.FileField(blank=True, upload_to='file/pkh/')),
                ('kip', models.FileField(blank=True, upload_to='file/kip/')),
                ('nama_ayah_kandung', models.CharField(blank=True, max_length=200)),
                ('agama_ayah_kandung', models.CharField(blank=True, max_length=200)),
                ('pekerjaan_ayah_kandung', models.CharField(blank=True, max_length=200)),
                ('nama_ibu_kandung', models.CharField(blank=True, max_length=200)),
                ('agama_ibu_kandung', models.CharField(blank=True, max_length=200, null=True)),
                ('pekerjaan_ibu_kandung', models.CharField(blank=True, max_length=200)),
                ('alamat_orang_tua', models.CharField(blank=True, max_length=200)),
                ('desa_orang_tua', models.CharField(blank=True, max_length=200)),
                ('kecamatan_orang_tua', models.CharField(blank=True, max_length=200)),
                ('kabupaten_orang_tua', models.CharField(blank=True, max_length=200)),
                ('provinsi_orang_tua', models.CharField(blank=True, max_length=200)),
                ('no_kk_wali_murid', models.CharField(blank=True, max_length=200)),
                ('p_no_kk_wali_murid', models.FileField(blank=True, upload_to='file/kk/walimurid/')),
                ('nama_wali_murid', models.CharField(blank=True, max_length=200)),
                ('agama_wali_murid', models.CharField(blank=True, max_length=200)),
                ('pekerjaan_wali_murid', models.CharField(blank=True, max_length=200)),
                ('alamat_wali_murid', models.CharField(blank=True, max_length=200)),
                ('desa_wali_murid', models.CharField(blank=True, max_length=200)),
                ('kecamatan_wali_murid', models.CharField(blank=True, max_length=200)),
                ('kabupaten_wali_murid', models.CharField(blank=True, max_length=200)),
                ('provinsi_wali_murid', models.CharField(blank=True, max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserSiswa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nik', models.CharField(max_length=16)),
                ('no_kk', models.CharField(max_length=16)),
            ],
        ),
    ]
