# Generated by Django 4.0.dev20210305062837 on 2021-03-17 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppdbpemkab', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSekolah',
            fields=[
                ('kode_sekolah', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('doc_code', models.CharField(max_length=200)),
                ('no_document', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='rfDocument',
            fields=[
                ('doc_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('desc', models.CharField(blank=True, max_length=40)),
                ('is_mandatory', models.BooleanField(blank=True, default=False)),
            ],
        ),
    ]
